# Generated by Django 2.2.4 on 2019-08-09 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tika', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='select_product',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.CharField(max_length=200),
        ),
    ]
