# Generated by Django 2.2.4 on 2019-08-07 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tika', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=10)),
                ('customer_phone', models.CharField(max_length=11)),
                ('location', models.CharField(max_length=2)),
                ('select_product_title', models.CharField(max_length=50)),
                ('select_product_quantity', models.IntegerField()),
                ('total_price', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
