# Generated by Django 2.2.4 on 2019-08-09 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tika', '0002_auto_20190809_1751'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='total_price',
            new_name='tot_price',
        ),
    ]
