# Generated by Django 2.2.4 on 2019-08-08 14:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tika', '0003_order_pub_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='select_product_quantity',
        ),
        migrations.RemoveField(
            model_name='order',
            name='select_product_title',
        ),
        migrations.RemoveField(
            model_name='order',
            name='total_price',
        ),
        migrations.AddField(
            model_name='order',
            name='select_product',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
