# Generated by Django 2.2.4 on 2019-08-08 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tika', '0004_auto_20190808_2336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='select_product',
            field=models.TextField(max_length=200),
        ),
    ]
