# Generated by Django 2.2.4 on 2019-08-08 15:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tika', '0005_auto_20190809_0038'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_price',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
    ]
